version: '3.9'

services: 
  backend:
    image: ghcr.io/harri200191/websitechangeanalyzer/backend:${BACKEND_TAG}
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI} 
    volumes:
      - ./backend/.env:/app/.env:ro

  frontend:
    image: ghcr.io/harri200191/websitechangeanalyzer/frontend:${FRONTEND_TAG}
    ports:
      - "4173:4173" 

  monitor:
    image: ghcr.io/harri200191/websitechangeanalyzer/monitor-app:${MONITOR_TAG}
    ports:
      - "8000:8000" 
    environment:
      - MONGO_URI=${MONGO_URI} 
    volumes:
      - ./monitor/.env:/app/.env:ro 
