name: Monitor Cue Cinemas Page (Dockerized)

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cue-monitor

jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base image
        run: |
          docker build -f Dockerfile.base -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-base:latest .
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-base:latest

      - name: Build app image
        run: |
          docker build -f Dockerfile.app -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest .
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Run monitor container
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        run: |
          docker run --rm \
            -e SENDER_EMAIL \
            -e SENDER_PASSWORD \
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
