name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          tags: ghcr.io/${{ github.repository_owner }}/cue-backend:latest
          push: true

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          tags: ghcr.io/${{ github.repository_owner }}/cue-frontend:latest
          push: true

      - name: Build and Push Monitor
        uses: docker/build-push-action@v5
        with:
          context: ./monitor
          file: ./monitor/Dockerfile.app
          tags: ghcr.io/${{ github.repository_owner }}/monitor:latest
          push: true
